version: "2"

services:
  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=dev
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./webapp:/webapp
    ports:
      - "${DJANGO_SETTINGS_PORT}:8000"
